### ISSUE TITLE
**시간 관리하기**

### ISSUE THREAD

**Issue by yoonucho** [hi-hyein/nyangterest#169]
*  집중타임 중 딴 짓(주로 youtube시청)은 뽀모도로 타이머 기준 25분씩 후 휴식 시간 (1턴- 5분, 4턴- 15분)에만  한다.

* 뽀모도로 타이머 오토 설정은 수동으로 다시 변경하고 내 의지에 대해 테스트해본다.

**Comment by yoonucho** [comment]
확실히 youtube 시청시간이 줄어들었다. 계속 이대로 진행할 생각이다.

**Comment by jongfeel** [comment]
이걸 Pin issue로 등록하면 좋을 듯 하네요. 제가 먼저 등록해 드릴게요.
나중에 Pin issue로 항상 노출되어야 하는 issue로 등록하고 싶으면 사용하시면 좋습니다.

모르실 것 같아서 스크린샷 첨부합니다.
![image](https://user-images.githubusercontent.com/17442457/81130124-91545e00-8f81-11ea-9508-f47e9b2e9062.png)

**Comment by yoonucho** [comment]
감사합니다!

**Comment by yoonucho** [comment]
계획한 시간에  할당량을 채워나가는 훈련을 했다고 생각합니다.
