### ISSUE TITLE
필터링을 다시 프론트엔드에서 하게 하면 어떨까?

### ISSUE THREAD

**Issue by yoonucho** [hi-hyein/nyangterest#174]
오늘 데이터구조를 변경하면서 든 생각이 지금 구조대로라면 필터링코드를 다시 프론트엔드로 옮겨놓아도 될거 같다라는 생각이 든다.

**Comment by jongfeel** [comment]
왜 그렇게 생각했는지 알 수 있을까요?

**Comment by yoonucho** [comment]
@jongfeel  

현재 데이터는  한 페이지씩이 아닌 전체데이터를 백엔드에서 이미 받아왔기 때문에 프론트엔드 내에 필터링코드가 있어도 가능할거 같습니다.

**Comment by jongfeel** [comment]
다시 질문 드리면 필터링에 필요한 변수가 4개가 있는데

1. 날짜
2. 품종
3. 검색어
4. 아이템 갯수

이걸 모두 프론트에서 하겠다는 얘기인가요?

**Comment by yoonucho** [comment]
@jongfeel  아아니요 저는 품종과 검색어입력시 코드를 생각했는데 글에는 제대로 설명이 안되긴했네요 또한 품종까지는 백엔드에 있어도 될거 같지만 검색어를 입력했을때  필터링코드는 프론트엔드에 넣어도 되지 않을까라고 생각하였습니다.

**Comment by jongfeel** [comment]
만약 그렇게 바꾼다면 설계 문서 수정이 필요하겠군요.

**Comment by yoonucho** [comment]
@jongfeel 우선 백엔드내에서 작동하게끔 코드를 수정하긴 했습니다.
브런치를 복사해서 프론트엔드내에서 코드를 작성해보고 어떤게 더 나을지 고민해보고 설계문서는 수정하도록 하겠습니다.

**Comment by jongfeel** [comment]
음
저는 먼저 설계 문서를 검토해서 수정해보고
또 어떤 문제가 있는지 체크를 해 봐야
코딩하다 안되는 문제를 찾는데 시간을 덜 쓸것 같다는 생각이거든요.

코딩의 branch가 아니라
설계 문서의 branch를 만들고 비교를 해보는거죠.

**Comment by yoonucho** [comment]
@jongfeel  아! 네 그런 방법도 있네요!

**Comment by yoonucho** [comment]
@jongfeel  검색어 입력 로직을 프론트엔드 내로 이동했을 때  변경된 설계문서입니다.

[유기동물 정보 조회 서비스의 검색 기능 설계서(plan B)](https://github.com/henyy1004/nyangterest/wiki/%EC%9C%A0%EA%B8%B0%EB%8F%99%EB%AC%BC-%EC%A0%95%EB%B3%B4-%EC%A1%B0%ED%9A%8C-%EC%84%9C%EB%B9%84%EC%8A%A4%EC%9D%98-%EA%B2%80%EC%83%89-%EA%B8%B0%EB%8A%A5-%EC%84%A4%EA%B3%84%EC%84%9C(plan-B))

**Comment by yoonucho** [comment]
이건 정말 될거같은데 이런 저런 핑계와 우선순위에 밀려서 시도도 못해봤었네요 ㅠㅠ
