### ISSUE TITLE
회원가입 코드 개선

### ISSUE THREAD

**Issue by hi-hyein** [hi-hyein/nyangterest#212]
- Fronend
  - [x] state 정리
  - [x] 이메일 중복체크 실시간으로 보여주기(helper text로 보여주기)
  - [x] validate 공통으로 빼기
  - [x] server의 회원가입 완료(welcome.html)페이지 compoenet화
  - [x] validate 체크로 인해 영향가는 코드 다시 훑어보기 (boolean 체크같은)

- Server
  - [x] 인증을 위한 `token` 생성 방식 다시 훑어보기

좀 더 명확한 이슈로 진행하는게 나을 것 같아 오늘 진행한 회원가입쪽의 세부계획내용으로 수정했습니다!

**Comment by henyy1004** [comment]
# 회원가입완료페이지 react component로 변경하기

## flow

### before

-   클라이언트에서 회원정보입력 후 서버로 전송
-   서버에서 회원가입 성공시 사용자에게 인증메일 전송
-   사용자가 인증을 완료하면 서버에서 welcome.html 응답

### after

-   클라이언트에서 회원정보입력 후 서버로 전송
-   서버에서 회원가입 성공시 사용자에게 인증메일 전송
-   사용자가 인증을 완료하면 서버에서 프론트 url 응답

## 필요한 것

1. 회원가입완료 react component
2. 회원가입완료페이지로 연결시킬 router

**Comment by hi-hyein** [comment]
- 개선이 필요하다! 생각했을 때 고처야한다.
