### ISSUE TITLE
Offline meeting, 2020-08-08

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/nyangterest#237]
### Gift: Refactoring: Improving the Design of Existing Code (2nd Edition)

- 다행히(?) ebook으로 출간되서 드리는 거니까 잘 보셨으면 좋겠습니다.
- javascript로 되어 있어서 좋을 수 있는데 1st edition은 C++ 이었습니다.
- 따라서 언어에 종속적이지 않은 어떤 마음가짐이나 기법을 알아간다는 느낌으로 보시면 좋습니다.

![image](https://user-images.githubusercontent.com/17442457/89766531-43786480-db33-11ea-929e-fa34313691e1.png)

**Comment by yoonucho** [comment]
감사합니다!

**Comment by henyy1004** [comment]
ebook 너무좋아요!!!
