### ISSUE TITLE
2020-09-02, 33th review meeting - postponed

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/nyangterest#249]
#212 번 관련 작업을 계속 진행 중이시고 작업 정리한 내용만 있네요.

논의할 내용이 없으므로 미팅 일정을 다음주로 미루겠습니다.
혹시 2주 후에 하고 싶다고 하시면 comment 주세요.

**Comment by henyy1004** [comment]
@jongfeel 

멘토님 안녕하세요!
넵 안그래도 정리한내용뿐이라 드릴 issue가 없어서 comment 남기려고했습니다!
그럼 다음주에 뵙겠습니다~~!!!

**Comment by hi-hyein** [comment]
## 1. 텍스트 입력시 뚝딱뚝딱(?) 입력됨, 전체삭제 불가
#252 관련 이슈였는데 텍스트 입력시 부드럽지 않고 입력될때마다 0.01초씩 멈추는 느낌을 받았고, 전체 삭제가 되지 않는 이슈가 있었습니다.
[수정작업 커밋](https://github.com/hi-hyein/nyangterest/commit/a0095384e11c134c56d6f5492ab48ab86d16e397#)
이부분에 대해 
```
1.텍스트 입력시 뚝딱뚝딱(?) 입력됨
해결방법 : 이메일 validate를 하기위해 서버로 fetch하여 반환값을 받아올때마다 
setState로 value값을 update해주고 있었다. 이 부분을 fetch 밖으로 이동시키니 정상작동하였다.

발생원인 : input event 발생시 바로 value가 update되지 않고 fetch->반환값리턴->value update
 이 순서로 update가 되어 시간차 때문에 뚝딱(?)거린게 아닌가 싶다.(정확하지않다.)

2.입력된 텍스트를 전체선택하여 지우는게 안됨
해결방법 : 1번과 동일
발생원인 : 전체선택하여 지웠을때 value는 공백이 되고 if(value==""){return}가 적용되어 함수는 바로 종료된다. 
value를 update해주는 setState는 공백이 아닐때 실행되는 fetch문 안에 있기때문에 실행되지 않아, 
value값은 업데이트 되지 않은 값이 그대로 내 ui에 보이게 되며 지워지지 않는 것 처럼 보이는 것 같다.
```
해결하며 발생원인을 이렇게 생각하긴 했는데 제가 원인을 맞게 이해한건지 궁금합니다!

## 2. object의 속성 변수에 담기 vs 그냥 바로 사용하기
params로 parameter를 받아 바로 params.email 이렇게 바로 이메일을 노출시키고 있는데, 새 변수에 담아서 노출시키는 게 나을지? 지금은 email 하나만 받아오고 그 사실은 내가 당연히 알고 있지만 만약 다른 사람이 이 params를 보았을 때 무엇이 얼마나 들어있는지는 코드로 확인을 해야 하니까, 작업자가 미리 변수에 담아두면 다음 사람이 확인하기 편하지 않을까 라고 생각했습니다.
https://github.com/hi-hyein/nyangterest/blob/8f1e90a15fee20839c82dd54b1ebaa63ebd1e011/packages/frontend/src/Components/Welcome.js#L26-L35

## 3. url에 email주소를 바로 요청하는 것 괜찮을까요?
http://127.0.0.1:3000/join/welcome/henyy1004@naver.com 이런 형태로 받으면 바로 메일 주소를 가져올 수 있어 편하긴 하지만, 메일 주소도 개인 정보니 url에 노출시키는 게 맞는지 모르겠습니다. 
검색해보니 어쩔 수 없이 쓰는 경우도 있고, 절대 안 된다는 의견도 있는데, 그렇다면 가장 안전하게 url에 토큰을 담아 보내고 서버에서 인증 후 해당 이메일을 프론트로 보내 처리하는 방법이 맞는지? 이 방법은 파라미터로 바로 받아오는 방법보다는 단계가 추가되어서 고민이 됩니다(단계가 추가되면 속도?차이가 생길까봐)
https://github.com/hi-hyein/nyangterest/blob/8f1e90a15fee20839c82dd54b1ebaa63ebd1e011/packages/backend/join.js#L118
