### ISSUE TITLE
google social login

### ISSUE THREAD

**Issue by hi-hyein** [hi-hyein/nyangterest#257]
## 하위 issue
- #260 냥터레스트 소셜로그인 요구사항
- #263 소셜로그인 use case 분석
- #264 소셜로그인 사용자 정보처리를 위한 분석 
- #266 소셜 로그인 설계
## 작업 관련 WIKI
- [oAuth & social login Wiki](https://github.com/hi-hyein/nyangterest/wiki/oAuth%EC%99%80-social-login)
- [소프트웨어 요구사항이란?](https://github.com/hi-hyein/nyangterest/wiki/소프트웨어-요구사항)
- [냥터레스트 요구사항](https://github.com/hi-hyein/nyangterest/wiki/냥터레스트-소셜로그인-요구사항)

**Comment by hi-hyein** [comment]
# 요구사항이란?
- 사용자가 필요로 하는 소프트웨어의 어떤 것들
- 소프트웨어를 개발하기 위해 이해 관계자들이 필요로 하는 것들
- 사용자의 관점에서 시스템이 제공해야 하는 기능, 데이터, 인터페이스 정의
- 사용자에게 무엇(what)을 제공할 것인가에 초점을 맞춤

## 1. 기능적 요구사항 
- 수행될 기능과 관련되어 입력과 출력 및 그들 사이의 처리과정 
- 목표로 하는 제품의 구현을 위해 소프트웨어가 가져야 하는 기능적 속성( 워드 프로세서에서 파일 저장 기능, 편집 기능, 보기 기능 )

## 2. 비기능적 요구사항 
- 제품의 품질 기준 등을 만족시키기 위해 소프트웨어가 가져야 하는 성능, 사용의 용이 성, 안전성과 같은 행위적 특성
- 시스템의 기능에 관련되지 않는 사항을 나타냄 ( 성능(응답 시간, 처리량), 사용의 용이성, 신뢰도, 보안성, 운용상의 제약, 안전성 등 ) 
- Product 요구사항: 성능, 용량, 사용성, 확장성, 신뢰성, 유지보수, 안전, 보안 등 
- Organizational 요구사항: 표준, 배포, 설치
- External 요구사항: 이 기종간 상호운용성, 법적/윤리적 준수 요건

## 요구사항 개발
### 1. 요구사항 수집/추출
- 고객이 원하는 요구사항을 수집
- 수집된 요구사항을 통해 개발되어야 하는 시스템에 대한 사용자 요구와 시스템 기능 및 제약사항을 식별하고 이해하는 단계 
- 고객의 최초 요구사항은 추상적이기 때문에 수주자는 정확한 요구사항을 파악 
- 요구사항은 계약 및 최초 산정의 기본이 됨 
- 요구사항 추출 기법 : 인터뷰, 시나리오
### 2. 요구사항 분석 
- 추출된 고객의 요구사항을 분석 기법을 이용하여 식별 가능한 문제들을 도출하고 요구 사항을 이해하는 과정 
- 참여자들로부터 참여자들로부터 추상적 요구사항을 명세서 작성 전에 완전하고 일관성 있는 요구사항 으로 정리하는 활동
- 시스템을 계층적이고 구조적으로 표현하여야 한다
- 외부 사용자와의 인터페이스 및 내부 시스템 구성요소 간의 인터페이스를 정확히 분석 하여야 한다 
- 분석단계 이후의 설계와 구현단계에 필요한 정보를 제공하여야 한다. 
#### 2-1 요구사항 분석 기법 
- 구조적 분석 
- 객체지향 분석
    - 요구사항을 사용자 중심의 시나리오 분석을 통해 유스케이스 모델(Usecase Model)로 구 축하는 것
    - 요구사항을 추출하고, 유스케이스의 실체화(Realization)과정을 통해 추출된 요구사항을 분석
### 3. 요구사항 명세 - 분석된 요구사항을 명확하고 완전하게 기록하는 것
- 시스템이 어떻게 수행될 것인가가 아닌 무엇을 수행할 것인가에 대한 기술 
- 명세 내용은 고객과 개발자 사이에서 모두가 이해하기 쉽고 간결하게 작성
- 요구사항을 쉽게 참조할 수 있도록 고유의 식별자를 가지고 번호화하고, 모든 요구사항이 동등한 것이 아니기 때문에 요구사항을 우선 순위화
- 요구사항 명세서는 시스템의 외부 행위를 기술하는 것으로, 특정한 구조나 알고리즘을 사용하여 설계하지 않도록 함
### 4. 요구사항 검증 
- 사용자 요구가 요구사항 명세서에 올바르게 기술되었는가에 대해 검토하는 활동

검증사항 | 설명
-- | --
무결성과 완전성 | 사용자의 요구를 에러 없이 완전하게 반영하고 있는가?
일관성 | 요구사항이 서로간에 모순되지 않는가?
명확성 | 요구분석의 내용이 모호함 없이 모든 참여자들에 의해 명확하게 이해될 수 있는가?
기능성 | 요구사항 명세서가 “어떻게” 보다 “무엇을”에 관점을 두고 기술되 었는가?
검증가능성 | 요구사항 명세서에 기술된 내용이 사용자의 요구를 만족하는가? 개발된 시스템이 요구사항 분석 내용과 일치하는지를 검증할 수 있는가?
추적 가능성 및 변경용이성 | 시스템 요구사항과 시스템 설계문서를 추적할 수 있는가?

## 유스케이스(Usecase) 다이어그램
- 사용자의 관점에서 시스템의 서비스 혹은 기능 및 그와 관련한 외부 요소를 보여주는 다이어그램
- 고객과 개발자가 함께 보며 요구사항에 대한 의견을 조율할 수 있다
![image](https://user-images.githubusercontent.com/29498125/92969171-6d68d200-f4b7-11ea-817a-9793f51420f4.png)
### Actor 
- 시스템 외부에 존재 
- 시스템과 상호작용하는 모든 것 
- 사람 , 다른 외부에 있는 시스템도 포함
### Use case
- 모델화 대상이 외부에 제공하는 서비스 
- 액터가 이용
### 관계정의
- 관련된 액터와 유즈케이스를 연결 
- 액터 !== 유즈케이스의 행위자
- 어디까지나 서로의 관련성을 나타냄
### 시스템경계
- 시스템화 대상 범위, 안쪽이 시스템화 대상 범위이고 바깥쪽이 범위 이외  생략 가능

## 요구사항을 잘 정의하려면?
### 1. 요구사항의 계층구조를 이해하라


요구사항의 계층 | 올바른 요구사항 유도 질문
-- | --
비즈니스 요구사항 | - 비즈니스에서 해결하고자 하는 문제 프로세스는? - 근본적인 목적이나 동기는 무엇인가? - 프로젝트 결과물을 사용하여 얻게 될 이익과 가치는?
사용자 요구사항 | - 사용자는 결과물을 사용해서 무엇을 할 수 있는가?
기능적 요구사항 | - 프로젝트 팀원들이 만들어야 하는 것은 무엇인가? - 반드시 동작해야(사용할 수 있어야) 하는 기능은? - 혹시 제가 빠뜨린 것이 있을까요?

### 2. 요구사항과 실제 구현결과는 다를 수 있음을 인지시켜라.
- 요구자(고객)는 최종 결과물의 스케치나 샘플 등을 보았을 뿐이며 거기에 개인적 상상이 더해져서 훌륭한 결과물을 기대하고 있게 된다. 하지만 언제나 그렇듯이 최종 결과물은 그런 상상과 상당한 차이가 있게 마련 
- 기대치와 좀더 고급인력, 긴 시간, 높은 원가는 정비례하며, 제한된 자원 하에서의 기대치와 결과는 항상 반비례한다.

### 3. 숨어있는 진짜 요구사항을 수집해라.
- 굳이 말로 안 해도 암묵적으로 알고 있을 것이라고 여기는 것들이 있다. 이런 것은 어련히 알아서 잘 알고 있거나 잘해 줄 것이라고 여기는 사항들이 있기 때문에 이러한 것에 대해 기록이 되어 있지 않으면 나중에 큰 오해의 소지가 된다.
- 일방적으로 질문하지 말아야 한다.
- 예외사항을 얘기해 줄 사람을 만나라.

### 4. 요구사항을 인터뷰하고 정리하는 양식을 활용하라.
- 요구사항 Categories와 요구사항 우선순위는 프로젝트 관리에 있어서 매우 중요
#### 4.1 요구사항 Categories
- Business requirements: 비즈니스와 프로젝트의 목표, 지침, 원칙
- Stakeholder requirements: 타 조직에 미치는 영향, 타 조직과 의사소통 수위 
- Solution(Quality) requirements: 기능요구, 기술표준, 품질요구, 교육지원 등
- Project requirements: 서비스, 안정성, 관련법 준수, 인수/이행조건 등

### 5. 요구사항 우선순위 (나한테 완전 필수!)
- Black(Morgue, Deceased): 사망 또는 구명 불가능한 상태
- Red(Immediate): 생명이 위독한 상태로 즉각 응급치료를 받아야 생존 가능한 상태 
- Yellow(Delayed): 초기 응급치료를 받고 잠시 기다릴 수 있는 상태 
- Green(Minor): 경상으로서 걸어 다닐 수 있으며 즉각 구급이송이 필요 없는 상태 

#### 5.1 프로젝트가 지연될 것 같으면?
- M(Must do): 반드시 꼭 해야 할 것, 꼭 필요한 것 
- S(Should do): 해야 할 것, 있어야 할 것 
- C(Could do): M과 S를 다 하고도 시간이 남으면 할 수 있는 것

#### 5.2 우선순위 유의사항
- M/S/C의 개수 비율은 1/3 
- M부터 완성하도록 계획 수립
- M만으로도 벅찰 수 있으니 S와 C까지 완성하겠다고 무리한 계획은 X 
- W: (Want to do, 하고 싶은 것)를 추가로 수용하는 경우도 있다. 이런 경우 우선순위가 뒤죽박죽으로 진행되어 상당한 일정지연이나 중요한 인도물의 기능들이 미달하게 된다.

**Comment by hi-hyein** [comment]
# FLOW
![flowchart](https://github.com/hi-hyein/nyangterest/blob/master/hi_report/wiki/socialLoginFlowchart.png?raw=true)
- 사용자가 소셜 로그인 시도
- DB > nyang_memeber table에서 email로 data filtering
- 중복된 계정(email)이 있다면 
  - DB > snsName filed로 data filtering
  - snsName filed가 null값이라면
    - 일반 로그인 로직으로 로그인 처리
  - snsName filed가 null값이 아니라면
    - 소셜 로그인 로직으로 로그인 처리
- 계정(email)이 없다면
  - DB > snsName , xpireDate filed에 정보 저장
  - 소셜 로그인 로직으로 로그인 처리

# 로그인 후 access token 처리
- oAuth2.0의 인증 방식의 특징은 access token과 refresh token을 사용하여 인증한다는 것
- access token과 refresh token은 인증성공시 동시에 발급되고, 만료시간이 정해져있다.
- access token의 만료시간은 짧고 refresh token은 길다.
- access token이 만료되면 refresh token을 사용하여 access token을 갱신해야됨

따라서
```
1. access token이 만료시 갱신해주는 로직 필요
2. refresh token 만료되면 로그아웃 처리 필요
```

## 1. Google
### 토큰 만료시간
| Acess Token    | Refresh Token                              |
|----------------|--------------------------------------------|
| 1시간 (3600초) | 만료시간이 따로 없고 만료되는 상황은 있다. |

#### Refresh Token이 만료되는 경우
* 사용자가 앱의 액세스를 취소
* 새로 고침 토큰이 6 개월 동안 사용되지 않았을 경우
* 사용자가 비밀번호를 변경했으며 새로 고침 토큰에 Gmail 범위가 포함되어 있을 경우
* 사용자 계정이 허용 된 (라이브) 새로 고침 토큰의 최대 수를 초과했을 경우
### 토큰 갱신 방법
#### 1. passport-oauth2-refresh 모듈 사용
```javascript
const passport = require('passport');
const refresh = require('passport-oauth2-refresh');
const GoogleStrategy = require("passport-google-oauth20").Strategy;
 
const strategy = new GoogleStrategy({
  clientID: GOOGLE_APP_ID,
  clientSecret: GOOGLE_APP_SECRET,
  callbackURL: "http://www.example.com/auth/google/callback"
},
function(accessToken, refreshToken, profile, done) {
  // Make sure you store the refreshToken somewhere!
  User.findOrCreate(..., function(err, user) {
    if (err) { return done(err); }
    done(null, user);
  });
});
 
passport.use(strategy);
refresh.use(strategy);
```
```javascript
refresh.requestNewAccessToken('facebook', 'some_refresh_token', function(err, accessToken, refreshToken) {
  // You have a new access token, store it in the user object,
  // or use it to make a new request.
  // `refreshToken` may or may not exist, depending on the strategy you are using.
  // You probably don't need it anyway, as according to the OAuth 2.0 spec,
  // it should be the same as the initial refresh token.
 
});
```
#### 2. API
- 메서드 : GET / POST
- 요청 URL : https://oauth2.googleapis.com/token
- 출력 포맷 : json
- 파라미터 : 

| Name          | Type    | Description                               |
|---------------|---------|-------------------------------------------|
| client_id     | string  | API 콘솔 에서 얻은 클라이언트 ID 입니다.  |
| client_secret | string  | API 콘솔 에서 얻은 클라이언트 암호 입니다 |
| grant_type    | integer | refresh_token                             |
| refresh_token | string  | 인증에 성공하고 발급받은 갱신 토큰        |
- 응답 : 

| Name              | Type    | Description                                                              |
|-------------------|---------|--------------------------------------------------------------------------|
| access_token      | string  | 접근 토큰, 발급 후 expires_in 파라미터에 설정된 시간(초)이 지나면 만료됨 |
| token_type        | string  | 접근 토큰의 타입으로 Bearer와 MAC의 두 가지를 지원                       |
| expires_in        | integer | 접근 토큰의 유효 기간(초 단위)                                           |
| scope        | string | 애플리케이션이 사용자를 대신하여 액세스 할 수있는 리소스를 식별하는 공백으로 구분 된 범위 목록                                 |


## 2. 카카오
### 토큰 만료시간
| Acess Token    | Refresh Token                              |
|----------------|--------------------------------------------|
| 2시간 (7200초) | 2개월 (만료가 1개월 남았을 때 access token이 갱신되면 둘다 재갱신된다) |

### 갱신 방법
#### API
- 메서드 : GET / POST
- 요청 URL : https://kauth.kakao.com/oauth/token
- 출력 포맷 : json
- 파라미터 : 

| Name          | Type   | Description                                                                                                                      | Required |
|---------------|--------|----------------------------------------------------------------------------------------------------------------------------------|----------|
| grant_type    | String | "authorization_code"로 고정                                                                                                      | O        |
| client_id     | String | 앱 생성 시 발급 받은 REST API                                                                                                    | O        |
| redirect_uri  | String | 인증 코드가 리다이렉트된 URI                                                                                                     | O        |
| code          | String | 인증 코드 받기 요청으로 얻은 인증 코드                                                                                           | O        |
| client_secret | String | 토큰 발급 시, 보안을 강화하기 위해 추가 확인하는 코드  [내 애플리케이션] > [보안]에서 설정 가능  ON 상태인 경우 필수 설정해야 함 | X        |
- 응답 : 

| Name                     | Type    | Description                                                               |
|--------------------------|---------|---------------------------------------------------------------------------|
| token_type               | String  | 토큰 타입, "bearer"로 고정                                                |
| access_token             | String  | 사용자 액세스 토큰 값                                                     |
| expires_in               | Integer | 액세스 토큰 만료 시간(초)                                                 |
| refresh_token            | String  | 인증에 성공하고 발급받은 갱신 토큰                                                 |
| refresh_token_expires_in | Integer | 리프레시 토큰 만료 시간(초)                                               |
| scope                    | String  | 인증된 사용자의 정보 조회 권한 범위  범위가 여러 개일 경우, 공백으로 구분 |

## 3. 네이버
### 토큰 만료시간
| Acess Token    | Refresh Token                              |
|----------------|--------------------------------------------|
| 1시간 (3600초) | ???????? |

### 갱신 방법
#### API
- 메서드 : GET / POST
- 요청 URL : https://nid.naver.com/oauth2.0/token
- 출력 포맷 : json
- 파라미터 : 

| Name    | Type   | Required | Description                                                     |
|---------------|--------|----------|-----------------------------------------------------------------|
| grant_type    | string | Y        | refresh_token                                                   |
| client_id     | string | Y        | 애플리케이션 등록 시 발급받은 Client ID 값                      |
| client_secret | string |     Y    | 애플리케이션 등록 시 발급받은 Client secret 값                  |
| refresh_token | string |     Y    | 네이버 사용자 인증에 성공하고 발급받은 갱신 토큰(refresh token) |
- 응답 : 

| Name              | Type    | Description                                                              |
|-------------------|---------|--------------------------------------------------------------------------|
| access_token      | string  | 접근 토큰, 발급 후 expires_in 파라미터에 설정된 시간(초)이 지나면 만료됨 |
| token_type        | string  | 접근 토큰의 타입으로 Bearer와 MAC의 두 가지를 지원                       |
| expires_in        | integer | 접근 토큰의 유효 기간(초 단위)                                           |
| error             | string  | 에러 코드                                                                |
| error_description | string  | 에러 메시지                                                              |

## 로그아웃
Access token이 유효할 때 로그아웃/삭제처리가 되니 먼저 Access token이 유효한지 검사한 후 로그아웃/삭제할 것

**Comment by hi-hyein** [comment]
@jongfeel 

멘토님 안녕하세요!

 sns login 회원 가입멤버의 database table,filed, 소셜 로그인 후 access token 만료 처리에 대해서 생각을 많이 해보았는데요!!
시간이 꽤 오래걸렸습니다 ..ㅎ

## sns login 회원 가입멤버의 database table,field
- **1 회원 table 분리**
먼저 일반회원과 sns가입회원의 table를 별도로 구성해서 관리하는게 좋을지 생각했어요.
일반회원, sns가입회원이 동일한 메일계정으로 사용할 수 있으니 구분 지을 수 있게 분리가 필요하다 생각했거든요!
그런데 계속 고민하다 보니까 별도로 관리하게 될 때 로그인 로직에서 효율적이지 않을 것 같더라구요. 예를 들면 계정 중복 검사를 할 때 두개의 테이블을 체크...그래서 기존 테이블에 `snsName`라는 field를 추가해서 이 곳에 가입한 소셜서비스 이름을 넣고 소셜서비스 이름으로 가입 회원이 구분될 수 있도록 하려고 계획해 보았는데, 테이블을 분리해야하는지, 하나로 관리해야 한다면 제 방법이 좋은 방법인지 궁금합니다!  

- **2 field type**
추가된 field 중 소셜 서비스 이름을  저장하는 `snsName`을 `VARCHAR(10)`으로 설정했는데, 이유는 3가지 소셜서비스는 정해져있고 고정이라고 생각했거든요, 그래서 어느정도 여유공간을 줄 수 있고 남은 공간을 공백으로 처리하지 않는 VARCHAR가 좋다고 생각했습니다!!
database field를 추가할때 불필요한 공간..?을 사용하지 않고 효율적으로 하고 싶었어요..ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ;;;
이게 효율적으로 설정한게 맞을까요...ㅎ


- **3 access token과 refresh token field**
처음엔  access token과 refresh token까지 모두 db에 저장하려고 했는데, session에 저장되어있고 어차피 갱신되는 토큰이니
db에 저장될 필요가 없을 것 같아 넣지 않는 것으로 계획했습니다. 필요 없는 field가 맞는지 궁급합니다!

- **4 db field에 xpireDate 추가**
access token이 만료되었을때 갱신작업이 추가로 필요합니다. 
처음엔 토큰이 만료되면 error page를 보여줄테니 state code를 받아서 갱신을 해줄까 생각을 했었는데,  state code로 갱신을 하게 되면 유저에게 연결이 끊긴 인터렉션을 보여주게 되니 이 방법은 아닌 것 같아서 `현재시간 - 만료시간`을 계산한 시간을 db에 저장해두고 해당 시간일 경우에 access token을 갱신을 하는 방법으로 다시 생각해보았습니다. 그래서 xpireDate field를 추가해주었는데......갱신 방법이 알맞은 방법일까요?
이 방법 외에 생각해본 부분은 모든 요청시마다 access token의 유효성을 체크하는 api를 요청하고 응답받아 처리하느 방법도 생각해 보았습니다..

## 로그인 후 access token 만료 처리
위 3번 db field에 xpireDate 추가의 질문고 겹치는 부분인데요.. 
access token 만료처리를 어떻게 해야 더 좋은 방법일지 감이 안잡힙니다 흑흑...

**Comment by jongfeel** [comment]
벌써 설계 단계에 들어가셨군요.

우선 답변을 먼저 해드리고 마지막에 해 드릴 얘기를 하겠습니다.

## Answers

### 회원 table 분리

구분을 해야할 필요가 있을 수도 있고 아닐 수도 있습니다. 최종적으로 필요한 데이터는 사용자 데이터이지 어떤 방법을 통해서 들어오는지는 방법의 차이니까요. 제가 결정해 드릴 수는 없고 분석을 더 해서 소셜 로그인시 들어오는 데이터로 기존 회원가입 처리하는 방식을 처리할 수 있는지를 확인해 보시면 될 거 같아요.

### varchar?

varchar는 원래 그런 용도로 쓰는 겁니다. 그정도 string 값의 공간은 낭비 축에도 안드니까 그냥 쓰세요.

### saved token?

token은 oauth를 하기 위해 필요한 값인데다, oauth 서버를 통해 처리하기 위한 값이므로 내 사이트에는 필요가 없습니다. 계획한 대로 하시면 되요.

### expireDate

이것도 oauth 서버가 알아서 알려주므로 내 사이트에서 판단할 필요가 없을 겁니다. 나온 결과를 그대로 전달만 해 줘도 충분합니다.

## Talk to somethings

### Understanding oauth2 

인증 처리를 내 사이트가 아닌 oauth2 서비스를 하는 사이트에서 하는 것이므로 진행하는데 필요한 프로세스에 대한 처리만 잘 해주면 저장해야 할 값들이 없다는 걸 알게 됩니다.
실제로 간단한 oauth2 인증 처리하는 코드를 짜 보시고 이해를 하는게 좋을 수 있겠네요. 코딩 먼저 하지 않았고 분석, 설계를 어느 정도 하셨으니 테스트를 빨리 해보시는 걸 추천드립니다.

### Signup before Sign in

지금은 로그인을 먼저 처리해서 기존에 회원가입이 되었다는 가정하에 처리를 하는데, 소셜 계정으로도 회원가입 처리를 할 수 있다면 조금 더 확실한 처리가 될 수 있습니다.

### More analysis

소셜 로그인 계정으로 회원가입을 받고 로그인을 하는 사이트 2~3 군데 정도 직접 회원가입, 로그인을 해 보시고 어떤 식으로 처리하는지 한번 분석해 보는 것도 좋을 수 있습니다. use case 분석이죠.

- 소셜 로그인 계정의 정보를 그대로 사용하고 회원가입을 처리하는지, 혹은 추가적인 정보를 더 입력받아서 처리하는지 확인
- 기존에 회원 가입이 되어 있는 상태에서 소셜 로그인을 시도하면 기존 계정과 통합하는지 혹은 별도의 계정으로 처리하는지도 사이트마다 정책이 다르므로 확인

### More things

꼭 분석->설계 순서대로 해야 하는 건 아니니까 제가 언급한 내용에 대해 분석을 조금 더 진행해 보시면 어떨까요?

**Comment by hi-hyein** [comment]
@jongfeel 

varchar ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
빵터졌어욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 머쓱ㅎ

네! 말씀해주신 내용에 대해서 직접 테스트해보면서 분석 진행해보겠습니다
아주아주 좋은답변 감사합니다아아아

**Comment by hi-hyein** [comment]
만들어진 데이터나 코드들을 완전히 수정해야 되는 상황이 많았다
소셜로그인은 프로젝트 초반에 계획된 내용이었는데
그 때 설계분석이 되었어야 했구나를 많이 느낌
