### ISSUE TITLE
냥터레스트 소셜로그인 요구사항

### ISSUE THREAD

**Issue by hi-hyein** [hi-hyein/nyangterest#260]
- [냥터레스트 소셜로그인 요구사항 Wiki](https://github.com/hi-hyein/nyangterest/wiki/%EB%83%A5%ED%84%B0%EB%A0%88%EC%8A%A4%ED%8A%B8-%EC%86%8C%EC%85%9C%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD)
- [소프트웨어 요구사항 Wiki](https://github.com/hi-hyein/nyangterest/wiki/%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4-%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD)
- #257

**Comment by hi-hyein** [comment]
@jongfeel 
멘토님 안녕하세요!
요구 사항 작성 중 몇 가지 궁금한 점이 생겨 코멘트 남깁니다!

## 1. 제약사항, 인터페이스 요구사항 중복
제약사항과 인터페이스 요구 사항이 거의 겹치는데
제가 두 개의 개념을 잘못 알고 작성해서 요구 사항이 겹치는 걸까요?
아니면 작은 단위?의 요구 사항이라 겹칠 수밖에 없는 걸까요.

## 2. 요구사항 검증 기준 명확성 vs 무엇을에 중점
'명확성'은 요구 사항이 여러 의미로 해석되지 않게 명확하게 작성되는 것이고
'무엇을에 중점'은 구체적인 방법에 대한 것을 상세하게 만들지 말고 나중에 설계단게에 고칠 수 있도록 작성하는 것
이라는 게시글? 을 보면서 이 부분이 좀 헷갈렸어요.

예를들어
`단어 30개를 10초에 처리한다.`라는 명확성있게 작성한 요구사항인데,
`무엇을에 중점`이라는 검증 기준으로는 맞지 않는 부분이잖아요? 
설계단계에서 20개를 15초에 처리하는 것으로 고칠 수 있게 작성해야하니까...?!
그렇다고 단어 최소 20개에서 30개 정도를 15초~20초 사이에 처리한다 라는건 너무 애매해서 안될 것 같구ㅋㅋㅋㅋㅋㅋㅋㅋㅋ.. 
이 부분도 제가 개념을 잘못 알고 있는 걸까욬ㅋㅋ..

**Comment by jongfeel** [comment]
### 1번의 경우

제약 사항이 인터페이스 요구사항일 수 있습니다. 자연스럽게 그렇게 만들어 지기도 하죠. 별도로 구분해서 정리해 놓으면 나중에 확인하거나 찾기 쉬워지는 정도일 겁니다. 제약 사항도 강력하게 걸지 마시고 그냥 상식적인 수준에서 해줘도 괜찮습니다. 돈받고 하는 프로젝트 아니니까요.

### 2번의 경우

명확성을 지키라는 건 애매하게 써서 나중에 분쟁의 소지가 없게 하는게 좋다 수준이지 꼭 명확한 요구사항을 정해서 달성해야 할 기능의 범주에 넣지 않아도 됩니다. 내 프로젝트를 하는데 이런 명확성이 요구되는 요구사항이 필요가 없다고 하면 빼면 되는 거고요. 필요한 내용인데 구체적이지 않다 그러면 더 구체적으로 작성해 보는게 좋을 거에요.

### 추가로

모든 요구사항의 여러가지 기준을 내 프로젝트에 다 만족시켜야 하는 건 아닙니다. 요구사항 문서의 템플릿이나 예제를 보고 내 프로젝트에 적용해서 내용을 채워 넣거나 맞게 고치는 작업 쯤으로 생각할 수 있는데 꼭 그렇게 하지 않아도 되요.
요구사항은 특별한 템플릿이나 예제를 참고해서 만들어 내는게 아니고 내가 만들어야 할 소프트웨어의 중요한 내용 중 어떤 내용이 담겨져 있어야 하고 그게 소프트웨어로 구현 가능한 범주인지 판단해 내는 작업이 더 중요합니다. 구현 불가능한 내용이나 이상한 내용은 쳐 내고, 꼭 필요하다고 생각되는 기능이나 조건을 상세하게 더 기술하는 쪽으로 하는게 좋습니다.
일단 정답은 없으니 필요한대로 적어 나가고 계속해서 수정 보완해 나가면 어느 정도 좋은 요구사항 문서를 만들 수 있습니다.

**Comment by jongfeel** [comment]
### One more thing

지난 미팅때 오래 얘기한 내용을 다시 기억해 보시면...
컴알못인 사람들에게 컴퓨터에서 돌아가는 물건을 만들어내야 하는 일을 하는 것이므로 불가능한 것들 (이상한 소리 하면서 만들어주세요 라는 얘기 짜르기), 어느 정도의 사이즈가 나오는지 각 재보는거 그리고 어느 정도의 기간이 필요할 것이다 까지 각을 재 보는 일을 하는 거라 보면 되요.
이런 터무니없이 만들어 주세요 급의 얘기를 잘 듣고 분석을 해 내서 그걸 소프트웨어로 만들어 낼 수 있는 문서로 만들어내는 작업이 가장 중요하므로, 내가 소프트웨어에 대해 얼마나 알고 있고 모르고 있는지 생각해 볼 수 있는 좋은 계기가 될거에요.

그런데 사실 냥터레스트는 누가 만들어 주세요 라고 하지 않은 프로젝트이므로 스스로 내 안의 또 다른 자아를 꺼내서 이런 저런 걸 만들거야라고 생각하신 걸 본래의 자아가 문서로 적는 짓을 하면 됩니다.
