### ISSUE TITLE
35th, schedule Schedule

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/nyangterest#262]
#### 주당: 6시간

- 평일 2회: 1시간씩
- 토, 일: 2시간씩

나중에 잊어버리지 않기 위해
가능하다면 매일 계획한대로 실천했는지 체크 하시고 기록해 주시면 좋겠습니다.
(알람 계속 와도 상관 없으니까 해주세요)

**Comment by hi-hyein** [comment]
- [ ] 오후 11시30분부터 12시30분까지

**Comment by hi-hyein** [comment]
#264 
- [ ] PM11:50 ~ AM01:50

**Comment by hi-hyein** [comment]
#264 
- [ ] PM11:30~ AM01:30

**Comment by hi-hyein** [comment]
#257 
- [ ] 오후11시 40분부터 오전 12시40분까지

**Comment by hi-hyein** [comment]
#266 

- [ ] 오후 11시 50분부터 오전 11시 50분까지

**Comment by hi-hyein** [comment]
#267 
- [ ] 오후 11시 30분부터 오전 1시 30분까지

**Comment by hi-hyein** [comment]
#267 
- [ ] 오후 11시 30분부터 오전 12시 30분까지

**Comment by hi-hyein** [comment]
#257
- [ ] 오후 11시30분뷰터 12시30분까지

**Comment by hi-hyein** [comment]
#267
- [ ] 오후11시30분부터 오전12시30분까지

**Comment by hi-hyein** [comment]
#270, #271
- [ ] 오후 11시30분 ~ 오전 1시 30분

**Comment by hi-hyein** [comment]
## 9/24 - 9/14 (6시간씩 3주)
총 18시간 중 15시간 진행 (83% 달성)
