### ISSUE TITLE
Propose divide small issues on you works

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/nyangterest#265]
문서 작업을 조금씩 진행하고 계신 것 같은데 사실상 issue에는 변화가 없어서 작업량을 추적하기가 어려운 것 같습니다.

그래서 문서 작업의 진행 사항도 다른 issue로 추가해서 관리하시는게 좋을 것 같습니다.

매 issue 마다 문서 link는 같지만 작업할 내용은 다르게 관리하는 거죠.

사실 혜인님의 경우는 1주당 시간 계획에 따르면 1시간씩 2회, 2시간씩 2회이므로 적어도 작업 계획 issue가 1주일에 4개는 등록이 되어야 합니다.

**Comment by hi-hyein** [comment]
네! 이슈를 좀더 세분화 해서 작게작게 관리해보도록 할게요!
