### ISSUE TITLE
테스트용 DB 스크립트 생성

### ISSUE THREAD

**Issue by hi-hyein** [hi-hyein/nyangterest#274]
테스트 코드를 위한 DB스크립트 만들기
- [x] 데이터 베이스, 테이블 생성
- [x] 생성된 데이터 베이스와 테이블 삭제

**Comment by hi-hyein** [comment]
# 오후 8시30분 ~ 9시30분
테스트 코드용 DB 스크립트 만들기 전 계획

## Test Database
- 기존 db는 aws에 연결되어 있음
- 그렇다면 aws에 테스트용 db를 생성하여 연동해야하나?
- 로컬에서 테스트 진행하도록 해보자

**Comment by hi-hyein** [comment]
# 오후 11시~ 오전1시
로컬호스트 db연결

## Localhost Database
- 테스트 전 mysql이 내 컴퓨터에 설치되어야함
- db는 스크립트에서 생성되어야함(로컬에서 mysql을 연결하기때문에 db는 각자 생성해줘야함)
- table도 스크립트로 생성되어야함

## 작업 중 문제
스크립트 코드로 로컬호스트 연결이 안되고 있음....
- Client does not support authentication protocol requested by server; consider upgrading MySQL client
- You must reset your password using ALTER USER statement before executing this statement.
- Your password does not satisfy the current policy requirements (code 1819)
비밀번호 변경해도 자꾸 위 에러만 나고 연결이 안됨

**Comment by hi-hyein** [comment]
@jongfeel 
멘토님 안녕하세요
테스트용 DB를 로컬에 설치해서 사용하는게 좋겠다!
라고 생각을 해서 그렇게 진행하려고 했는데요
만약에 다른개발자가 테스트 코드를 사용한다면? 이라는 생각이 드니까
로컬에 테스트용 DB를 설치하는게 맞을까? 생각이들더라구요
왜냐하면 로컬에 mysql을 설치해야 테스트코드를 사용할 수  있으니까요..!
- 테스트용 db 로컬에 설치해서 사용하는게 상관없는지
- 지금 사용중인 aws서버 mysql을 사용하는게 좋은지

**Comment by jongfeel** [comment]
좋은 고민입니다.

두 가지 방법 다 나쁘지 않은 것 같아요.

중요한건 세팅하는 방법에 대한 내용이 적힌 문서를 잘 만들어야 한다는 점입니다.

맞다고 생각하는 방향으로 진행하시면 됩니다.
