### ISSUE TITLE
Resolve opened issues.

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/nyangterest#280]
프로젝트가 종료가 되었으므로 기존 issue들을 간단하게 코멘트 달고 close 했으면 좋겠습니다.

회고에 대한 issue 하나만 open으로 남겨두고 거기에 회고 내용에 대한 링크를 추가하면 좋을 것 같아요.

**Comment by yoonucho** [comment]
@jongfeel 멘토님 그럼 여기에 코멘트로 링크를 넣으면 될까요?

**Comment by jongfeel** [comment]
회고 issue를 만드는게 나은 것 같아요.

- 회고 issue 생성
- 회고 문서가 있는 link 추가
- README.md에도 회고 문서가 있는 link 추가

**Comment by yoonucho** [comment]
@jongfeel  네 알겠습니다!

**Comment by jongfeel** [comment]
#282 생성 확인
